### PR TITLE
Account activated

### PR DESCRIPTION
**Pull request by phucynwa**

### CODE REVIEW

**Comment by phucynwa** [comment]
ready

**Comment by phucynwa** [comment]
ready

**Comment by phucynwa** [comment]
https://dev.framgia.com/issues/184325

**Comment by hungnh103** [comment]
commented
Your code in User model is duplicating now. Please review it again.

**Comment by phucynwa** [comment]
ready

**Comment by phucynwa** [comment]
ready

**Comment by phucynwa** [comment]
ready

**Comment by hungnh103** [comment]
merged

**Pull request merged**
